---
title: "Practical One"
output: html_document
---

# 1. Find all rows in airquality with missing values

```{r, echo=FALSE}
data("airquality")
```

```{r}
missing <- airquality[!complete.cases(airquality), ]
missing
#42 rows with missing value
```

# 2. Summary Statistics for airquality Data

## Tempurature

### Mean

```{r}
mean(airquality$Temp, na.rm = TRUE)
```

### Std Deviation

```{r}
sd(airquality$Temp, na.rm = TRUE)
```

### Min

```{r}
min(airquality$Temp)
```

### Max

```{r}
max(airquality$Temp)
```

## Ozone Level

### Mean

```{r}
mean(airquality$Ozone, na.rm = TRUE)
```

### Std Deviation

```{r}
sd(airquality$Ozone, na.rm = TRUE)
```

### Min

```{r}
min(airquality$Ozone, na.rm = TRUE)
```

### Max

```{r}
max(airquality$Ozone, na.rm = TRUE)
```

# Linear Regression Model

### Load car data

```{r}
data("cars")
```

## Fitted model

```{r}
Y <- cars$dist
x <- cbind(1, cars$speed)
```

## Parameter Estimates

```{r}
beta_coeff <- solve(t(x) %*% x) %*% t(x) %*% Y
```

## lm() model

```{r}
model <- lm(dist ~ speed, data = cars)
summary(model)
```

## Regression Summary Function

```{r}
F <- function(x, y){
  #beta estimate
  be <- solve(t(x) %*% x) %*% t(x) %*% Y
  
  #residuals
  y_hat <- x %*% be
  residuals <- y - y_hat
  
  #variance
  n <- nrow(x)
  p <- ncol(x)
  dof <- n-p
  sig_sq <- sum(residuals^2)/ (dof)
  
  #std error
  covM <- sig_sq * solve(t(x) %*% x)
  std_error <- sqrt(diag(covM))
  
  #T-values
  t_val <- be / std_error
  
 #Summary table
  sum_tab <- data.frame(
    Estimate = as.vector(be),
    StdError = std_error,
    Tvalue = t_val
  )
  
  return(sum_tab)
}
result <- F(x,Y)
print(result)
```

## Matrix Calculations

```{r}
print(beta_coeff)
```

```{r}
print(coef(model))
```

### Same values for beta estimates and the model
